// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAlVO98vwrBuIbHrZBu8H6OwHC9e2fnnY',
    appId: '1:958731587254:web:4f601606b28706ec3ea017',
    messagingSenderId: '958731587254',
    projectId: 'emart-f324b',
    authDomain: 'emart-f324b.firebaseapp.com',
    storageBucket: 'emart-f324b.appspot.com',
    measurementId: 'G-VD81SHKLNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PmQh0V23mNzBBm6rQIWb_YEnWVJYwJw',
    appId: '1:958731587254:android:39121ca677e463a13ea017',
    messagingSenderId: '958731587254',
    projectId: 'emart-f324b',
    storageBucket: 'emart-f324b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCF4HaGiDMPunrF8jarioXH3N0ENbF0Y',
    appId: '1:958731587254:ios:612ec92672a80d413ea017',
    messagingSenderId: '958731587254',
    projectId: 'emart-f324b',
    storageBucket: 'emart-f324b.appspot.com',
    iosClientId: '958731587254-d62asep07je00sscjef92k99fjvqfas5.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCF4HaGiDMPunrF8jarioXH3N0ENbF0Y',
    appId: '1:958731587254:ios:14926a25478753ed3ea017',
    messagingSenderId: '958731587254',
    projectId: 'emart-f324b',
    storageBucket: 'emart-f324b.appspot.com',
    iosClientId: '958731587254-8oguom20gj6ihingk5jq19if4onm61s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart.RunnerTests',
  );
}
